---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: 1/15 - Update Yum
      yum:
        update_cache: yes
    
    - name: 2/15 - Install updates
      yum:
        name: "*"
        state: latest

    - name: 3/15 - install dependencies
      yum:
        name: "{{ package }}"
        state: present
      vars:
        package:
        - wget
        - git
        - maven
        - docker

    - name: 4/15 - Start docker
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: 5/15 - install JDK 11
      command: amazon-linux-extras install java-openjdk11 -y

    - name: 6/15 - download Jenkins config
      git:
        repo: https://github.com/aestebance/jenkins-default-config.git
        dest: /tmp/jenkins

    - name: 7/15 - Setup Jenkins Repo
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    
    - name: 8/15 - Import Jenkins Repo GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
 
    - name: 9/15 - install Jenkins
      yum:
        name: jenkins
        state: present

    - name: 10/15 - Temporarily Stop Jenkins
      service: 
        name: jenkins 
        state: stopped
   
    - name: 11/15 - Modify user shell
      user:
        name: jenkins
        shell: /bin/bash
    
    
    # - name: 9/13 - Delete Jenkins default dir
    #   file:
    #     state: absent
    #     path: /var/lib/jenkins
    
    - name: 12/15 - Copy over cloned Jenkins /var/lib/jenkins
      copy:
        remote_src: yes
        src: /tmp/jenkins/jenkins
        dest: /var/lib
        
         
    - name: 13/15 - Restore jenkins user ownership on /var/lib/jenkins
      file:
        path: /var/lib/jenkins
        state: directory
        recurse: yes
        owner: jenkins

    - name: 14/15 - Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: 15/15 - Wait until Jenkins is up
      uri:
        url: "http://127.0.0.1:8080"
        status_code: 403
      register: result
      until: result.status == 403
      retries: 60
      delay: 1